---
language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"
env:
  global:
    - GIT_COMMITTER_NAME=mickaneda
    - GIT_COMMITTER_EMAIL=Michiru.Kaneda@gmail.com
    - GIT_AUTHOR_NAME=mickaneda
    - GIT_AUTHOR_EMAIL=Michiru.Kaneda@gmail.com
before_install:
  - openssl aes-256-cbc -K $encrypted_b46fb5af9050_key -iv $encrypted_b46fb5af9050_iv -in .travis_enc.tar.enc -out .travis_enc.tar -d
  - tar xf .travis_enc.tar
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - cp gcpm_travis_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - mv gcpm.yml tests/data/
  - mv gcpm_oauth.yml tests/data/
  - mv service_account.json tests/data/
  - mkdir -p ~/.config/gcpm/
  - mv oauth ~/.config/gcpm/
  - chmod 600 ~/.config/gcpm/oauth
install:
  - 'curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python'
  - export PATH="$HOME/.poetry/bin:$PATH"
  - poetry install
script:
  - ./manage.sh test
after_script:
  - cd htmlcov
  - git init
  - git checkout -b gh-pages
  - git add -A
  - git commit -m "Coverage check [ci skip]"
  - git remote set-url --push origin git@github.com:mickaneda/gcpm
  - git push -u -f origin gh-pages
notifications:
  email:
    recipients:
      - Michiru.Kaneda@gmail.com
    on_success: change
    on_failure: always
