[tool.poetry]
name = "gcpm"
version = "0.1.0"
description = "HTCondor pool manager for Google Cloud Platform."
repository = "https://github.com/mickaneda/gcp_condor_pool_manager"
homepage = "https://github.com/mickaneda/gcp_condor_pool_manager"
authors = ["Michiru Kaneda <Michiru.Kaneda@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"
keywords = []

[tool.poetry.dependencies]
python = "^2.7 || ^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
gcpm = "gcpm.gcpm:main"
